name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{mes-secrets.DOCKER_USERNAME}}
        password: ${{mes-secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: |
        docker build -t ${{mes-secrets.DOCKER_USERNAME}}/app:${{github.sha}} .
        docker tag ${{mes-secrets.DOCKER_USERNAME}}/app:${{github.sha}} ${{mes-secrets.DOCKER_USERNAME}}/app:latest

    - name: Push Docker image
      run: |
        docker push ${{ mes-secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
        docker push ${{ mes-secrets.DOCKER_USERNAME }}/app:latest
