name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t anessbs/hello-word-app:${{ github.sha }} .
        docker tag anessbs/hello-word-app:${{ github.sha }} anessbs/hello-word-app:latest

    - name: Push Docker image
      run: |
        docker push anessbs/hello-word-app:${{ github.sha }}
        docker push anessbs/hello-word-app:latest